version: '3.8'

services:
  # NestJS Application (using RDS for database)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sports-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-7d}
      PORT: 3000
    command: sh -c "npx prisma migrate deploy && node dist/main"

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: sports-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - app